version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:alpine"

    ports:
      - "5672:5672"

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  celery:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: celery -A tasks worker -l info --without-mingle --without-gossip
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/local_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    restart: on-failure



  beats:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: celery -A tasks beat #-l info  --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    restart: on-failure

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"